[package]
name = "AR-Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.93.5"
image = "0.25.5"
mediapipe-rs = {git = "https://github.com/WasmEdge/mediapipe-rs.git" }
wasi = "0.13.3"
wasi-nn = "0.6.0"

